plt.plot(true_positions, label="Measured", marker="o")
plt.plot(estimated_positions, label="Kalman Estimated", linestyle="--")
plt.plot(predicted_positions, label="Predicted", linestyle=":")
plt.legend()
plt.xlabel("Time (Chirp index)")
plt.ylabel("Range (m)")
plt.title("Kalman Filter Based Target Tracking")
plt.grid(True)
plt.show()
